/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mediamanager.gui;

import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 *
 * @author Josue
 */
public class MediaImagePosterPanel extends javax.swing.JPanel {

    private BufferedImage img;
    /**
     * Creates new form MediaImagePosterPanel
     */
    public MediaImagePosterPanel(String type) {
        initComponents();
        img = mediamanager.imgs.ReferenceImageClass.getRandomPoster(type);
    }
    
    @Override
    protected void paintComponent(Graphics g) {
         
        if(img != null)
        {
            g.drawImage(img, 0, 0, this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
