/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mediamanager.gui;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import mediamanager.videos.UploaderVideoTracker;

/**
 *
 * @author Josue
 */
public class ProgressBarFrame extends javax.swing.JDialog {

    JLabel _message;
    JProgressBar _progressBar;
    
    /**
     * Creates new form ProgressBarFrame
     */
    public ProgressBarFrame(byte[] data, String mediaType, String extention, String name) {
        initComponents();
        
        JPanel _mainPanel = InternalGUICreator.createBackgroundPanel(0, 0, 510, 75);
        this.add(_mainPanel);
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Uploading video clip...");
        this.toFront();
        this.setModalityType(ModalityType.APPLICATION_MODAL);
        
        _message = InternalGUICreator.createLabel("", 10, 15, 180, 20, false);
        _progressBar = InternalGUICreator.createJProgressBar(200, 10, 250, 30);
        
        _mainPanel.add(_message);
        _mainPanel.add(_progressBar);
        
        UploaderVideoTracker uploader = new UploaderVideoTracker(data, mediaType, extention, name, _progressBar,_message);
        uploader.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
